#!/bin/bash
# echo "Git Grep from Navigator"
cd ..
git grep -F '#!/usr/bin/env python' >> /home/lewis/mil_ws/src/NaviGator/pythonProgramList/pythonPrograms.txt
# echo "Searching for .py files"
find . -type f -name "*.py" >> /home/lewis/mil_ws/src/NaviGator/pythonProgramList/pythonPrograms.txt
